{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "08dfa2d8-0d2a-4494-8eda-64cea023da15",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "           Date      Open      High       Low    Close*        VOLUME\n",
      "0     25-May-22  3,929.59  3,999.33  3,925.03  3,978.73    100,000.00\n",
      "1     24-May-22  3,942.94  3,955.68  3,875.13  3,941.48    200,000.00\n",
      "2     23-May-22  3,919.42  3,981.88  3,909.04  3,973.75    300,000.00\n",
      "3     20-May-22  3,927.76  3,943.42  3,810.32  3,901.36    400,000.00\n",
      "4     19-May-22  3,899.00  3,945.96  3,876.58  3,900.79    500,000.00\n",
      "...         ...       ...       ...       ...       ...           ...\n",
      "1165   9-Oct-17  2,551.39  2,551.82  2,541.60  2,544.73  1,500,000.00\n",
      "1166   6-Oct-17  2,547.44  2,549.41  2,543.79  2,549.33  1,600,000.00\n",
      "1167   5-Oct-17  2,540.86  2,552.51  2,540.02  2,552.07  1,700,000.00\n",
      "1168   4-Oct-17  2,533.48  2,540.53  2,531.80  2,537.74  1,800,000.00\n",
      "1169   3-Oct-17  2,530.34  2,535.13  2,528.85  2,534.58  1,900,000.00\n",
      "\n",
      "[1170 rows x 6 columns]\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "# Get the data\n",
    "#from pyodide.http import open_url\n",
    "\n",
    "df_ = pd.read_csv('http://127.0.0.1:8000/sample.csv')\n",
    "print(df_)\n",
    "#url = 'https://raw.githubusercontent.com/alanjones2/uk-historical-weather/main/data/Heathrow.csv'\n",
    "#url_content = open_url(url)\n",
    "#df = pd.read_csv(url_content)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "9cca5bef-044a-46bd-bdf9-9c0790fa617e",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [26/Jun/2022 18:54:28] \"GET / HTTP/1.1\" 200 -\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 54635)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\socketserver.py\", line 316, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\socketserver.py\", line 347, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\socketserver.py\", line 360, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\socketserver.py\", line 747, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\http\\server.py\", line 427, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\http\\server.py\", line 415, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_19800\\4050432816.py\", line 10, in do_GET\n",
      "    self.wfile.write(\"received get request\")\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\socketserver.py\", line 826, in write\n",
      "    self._sock.sendall(b)\n",
      "TypeError: a bytes-like object is required, not 'str'\n",
      "----------------------------------------\n",
      "127.0.0.1 - - [26/Jun/2022 18:54:34] \"GET /favicon.ico HTTP/1.1\" 200 -\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 54636)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\socketserver.py\", line 316, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\socketserver.py\", line 347, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\socketserver.py\", line 360, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\socketserver.py\", line 747, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\http\\server.py\", line 427, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\http\\server.py\", line 415, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_19800\\4050432816.py\", line 10, in do_GET\n",
      "    self.wfile.write(\"received get request\")\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\socketserver.py\", line 826, in write\n",
      "    self._sock.sendall(b)\n",
      "TypeError: a bytes-like object is required, not 'str'\n",
      "----------------------------------------\n",
      "127.0.0.1 - - [26/Jun/2022 18:54:37] \"GET / HTTP/1.1\" 200 -\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 54641)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\socketserver.py\", line 316, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\socketserver.py\", line 347, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\socketserver.py\", line 360, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\socketserver.py\", line 747, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\http\\server.py\", line 427, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\http\\server.py\", line 415, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_19800\\4050432816.py\", line 10, in do_GET\n",
      "    self.wfile.write(\"received get request\")\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\socketserver.py\", line 826, in write\n",
      "    self._sock.sendall(b)\n",
      "TypeError: a bytes-like object is required, not 'str'\n",
      "----------------------------------------\n",
      "127.0.0.1 - - [26/Jun/2022 18:54:37] \"GET /favicon.ico HTTP/1.1\" 200 -\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 54642)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\socketserver.py\", line 316, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\socketserver.py\", line 347, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\socketserver.py\", line 360, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\socketserver.py\", line 747, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\http\\server.py\", line 427, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\http\\server.py\", line 415, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Temp\\ipykernel_19800\\4050432816.py\", line 10, in do_GET\n",
      "    self.wfile.write(\"received get request\")\n",
      "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\lib\\socketserver.py\", line 826, in write\n",
      "    self._sock.sendall(b)\n",
      "TypeError: a bytes-like object is required, not 'str'\n",
      "----------------------------------------\n",
      "\n",
      "KeyboardInterrupt\n",
      "\n"
     ]
    }
   ],
   "source": [
    "from http.server import BaseHTTPRequestHandler, HTTPServer # python3\n",
    "class HandleRequests(BaseHTTPRequestHandler):\n",
    "    def _set_headers(self):\n",
    "        self.send_response(200)\n",
    "        self.send_header('Content-type', 'text/html')\n",
    "        self.end_headers()\n",
    "\n",
    "    def do_GET(self):\n",
    "        self._set_headers()\n",
    "        self.wfile.write(\"received get request\")\n",
    "\n",
    "    def do_POST(self):\n",
    "        '''Reads post request body'''\n",
    "        self._set_headers()\n",
    "        content_len = int(self.headers.getheader('content-length', 0))\n",
    "        post_body = self.rfile.read(content_len)\n",
    "        self.wfile.write(\"received post request:<br>{}\".format(post_body))\n",
    "\n",
    "    def do_PUT(self):\n",
    "        self.do_POST()\n",
    "\n",
    "host = ''\n",
    "port = 80\n",
    "HTTPServer((host, port), HandleRequests).serve_forever()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
